# Generated by Django 4.2.11 on 2024-04-10 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_document_nom_ent_alter_document_prov_ent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='num_clusters',
            field=models.IntegerField(choices=[('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='3'),
        ),
    ]
