# Generated by Django 4.2.11 on 2024-04-17 13:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_document_num_clusters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(upload_to='docs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv'], message='Solo se permiten archivos CSV.')]),
        ),
    ]
