# Generated by Django 4.2.11 on 2024-04-17 13:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_document_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentPrediccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='docs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv'], message='Solo se permiten archivos CSV.')])),
                ('num_clusters', models.IntegerField(choices=[(2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3)),
            ],
        ),
    ]
