# Generated by Django 4.2.11 on 2024-04-23 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_documentprediccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebScrapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='Ingresa una URL')),
            ],
        ),
    ]
