# Generated by Django 4.2.11 on 2024-04-23 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_webscrapping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webscrapping',
            name='url',
            field=models.URLField(),
        ),
    ]
