# Generated by Django 4.2.11 on 2024-04-23 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_webscrapping_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='webscrapping',
            name='year',
            field=models.DateField(default='2020-12-02'),
        ),
    ]
