# Generated by Django 4.2.11 on 2024-04-23 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_webscrapping_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webscrapping',
            name='year',
            field=models.CharField(choices=[('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024')], default='2020', max_length=10),
        ),
    ]
